### PR TITLE
Create project section to portfolio page

### PR DESCRIPTION
**Pull request by eamador1**
Since my last review and merge, I worked on the following:

- [ ] Create a new branch called projects
- [ ] Add a background image
- [ ] Add project section
- [ ] run linters 

// I understand the project is incomplete, but I would like your review to progress. //

### CODE REVIEW

**Review by abdulhamiid — CHANGES_REQUESTED** [review]
Hi @eamador1 👋, 

# Requires Changes 🍀

Good job working on your project 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

### ♦♦♦ IMPORTANT
As you have only implemented a little part of the [project requirements.](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md)

Your design
image

Please kindly complete the "Works" section and add the "About myself" section (placed after the projects and before the contact form): using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

It is important that we try and complete our project by Implementing all the [section requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md) before requesting a review. 🤔

Let's follow the [project core requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md) for professional projects, and if we practice from our learning phase, it will be easier in the future at the industry level. Here is an article on [The importance of understanding software requirements](https://www.freecodecamp.org/news/why-understanding-software-requirements-matter-to-you-as-a-software-engineer/) 💪


## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by eamador1** [comment]
Since my last review, I worked on the following:

- [ ] Add and finish content of portfolio project
- [ ] Use header tags were required.
- [ ] Use grid as the main container for the "cards" project
- [ ] Work on the sections to match the template

**Review by V-Blaze — COMMENTED** [review]
Hi @eamador1, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request 🔴 🟥 
download

- [ ] You submitted a pull request that has already been reviewed by a code reviewer as a first review in your dashboard. Please make sure you request for review for the correct project milestone in your dashboard. If you are repeating the week, please create a new branch and a new pull request for this project. thanks 😄 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by eamador1** [comment]
@V-Blaze 👏🏼 
I do not understand how I messed it up.

So I created a branch called "projects" on Saturday to do the work section, after merging the previous branch with the main for the project's first section. And now you are telling me I should create a new branch? What do I do with the branch "projects"? As far as I know, I am not supposed to merge it, because it has not been approved. Please, I kindly ask for clarification.

Now, what I do not know is how come I have three pull requests. As I said before, I do not know how I messed it up.

**Comment by eamador1** [comment]
Hello @V-Blaze ,
One more thing, I did make a pull request on Saturday.  This should be my second review, as far as I understand. Or since I am repeating week one, the reviews reset to zero? Thank you for your help.

**Comment by V-Blaze** [comment]
> Hello @V-Blaze , One more thing, I did make a pull request on Saturday. This should be my second review, as far as I understand. Or since I am repeating week one, the reviews reset to zero? Thank you for your help.

Hello, you don't need to merge this branch to main as it has not been approved.. here's what you need to do. 

- While you are in your git terminal or vscode terminal, checkout this branch.
- Then while you are still on this branch 'projects', create a new branch with this command `git checkout -b new-brach-name` NB: change the 'new-branch-name' to the name you want to give your branch,
-  Then you can push the new branch to GitHub by running `git push -u origin then the branch name`.
- Then you can create a pull request from that branch.

And to answer your second question, Yes, your review for each project reset to zero if you are repeating the week.

**Comment by eamador1** [comment]
Hello @V-Blaze,

I did what you suggested and I created pull request #4. How do I make it to start from scratch?

**Comment by V-Blaze** [comment]
> Hello @V-Blaze,
> 
> I did what you suggested and I created pull request #4. How do I make it to start from scratch?

Hello... That's nice 👍 ..  What do you mean by 'start from scratch'?

**Comment by eamador1** [comment]
Hi @V-Blaze . I am not following you. You requested me to make another pull request because the pull request number was 3 and not 1 or 2. Isn't it? I am all confused? 

You  wrote "You submitted a pull request that has already been reviewed by a code reviewer as a first review in your dashboard. Please make sure you request for review for the correct project milestone in your dashboard. " I was guessing it had to be pullrequest#2. 

I am sorry but I am lost.

**Pull request merged**
